parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'
    articles_directory: '%upload_directory%/articles'
    podcasts_directory: '%upload_directory%/podcasts'
    archives_directory: '%upload_directory%/archives'
    enseignements_directory: '%upload_directory%/enseignements'
    users_directory: '%upload_directory%/users'
    thumbnail_sizes:
        small: { width: 150, height: 150 }
        medium: { width: 400, height: 400 }
        large: { width: 800, height: 600 }
    adminlte:
        skin: 'blue'
        layout: 'fixed'
        brand_logo: '/assets/images/logo/logo.png'
        brand_text: 'Kong Administration'
    kong:
        site_name: 'Portail Islamique de Kong'
        site_description: 'Sauvegarder et valoriser la tradition islamique de Kong'
        supported_languages: ['fr', 'ar', 'en']
        default_language: 'fr'
        pagination_limit: 20

    App\Entity\:
        resource: '../src/Entity'
        exclude: true

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Service\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'

    App\Service\AdminStatisticsService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\ImageProcessor:
        arguments:
            $uploadDirectory: '%upload_directory%'
            $thumbnailSizes: '%thumbnail_sizes%'

    App\Service\ContentManager:
        arguments:
            $fileUploader: '@App\Service\FileUploader'
            $imageProcessor: '@App\Service\ImageProcessor'

    App\Service\SearchService:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'

    App\Service\ApiResponseService:
        arguments:
            $serializer: '@serializer'

    App\Service\NotificationService:
        arguments:
            $mailer: '@mailer'
            $twig: '@twig'

    App\Service\CacheService:
        arguments:
            $cache: '@cache.app'

    App\EventListener\ContentUploadListener:
        arguments:
            $slugger: '@Symfony\Component\String\Slugger\SluggerInterface'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    App\EventListener\UserActivityListener:
        tags:
            - { name: kernel.event_listener, event: security.interactive_login }

    App\Twig\AdminExtension:
        tags: ['twig.extension']

    App\Twig\KongExtension:
        arguments:
            $kongSettings: '%kong%'
        tags: ['twig.extension']

    App\Security\ArticleVoter:
        tags: ['security.voter']

    App\Security\PodcastVoter:
        tags: ['security.voter']

    App\Security\EnseignementVoter:
        tags: ['security.voter']

    App\Command\ImportArchivesCommand:
        arguments:
            $entityManager: '@doctrine.orm.entity_manager'
            $fileUploader: '@App\Service\FileUploader'
        tags: ['console.command']

    App\Command\GenerateStatisticsCommand:
        arguments:
            $statisticsService: '@App\Service\AdminStatisticsService'
        tags: ['console.command']

when@dev:
    services:
        App\Service\DevDataLoader:
            arguments:
                $entityManager: '@doctrine.orm.entity_manager'
                $userPasswordHasher: '@security.user_password_hasher'

when@prod:
    services:
        App\Service\ContentCacheService:
            arguments:
                $cache: '@cache.adapter.redis'

when@test:
    services:
        App\Service\TestDataFactory:
            arguments:
                $entityManager: '@doctrine.orm.entity_manager'